
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author franklin chidera
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenuBar5 = new javax.swing.JMenuBar();
        jMenu13 = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        jMenuBar6 = new javax.swing.JMenuBar();
        jMenu15 = new javax.swing.JMenu();
        jMenu16 = new javax.swing.JMenu();
        jMenuBar7 = new javax.swing.JMenuBar();
        jMenu17 = new javax.swing.JMenu();
        jMenu18 = new javax.swing.JMenu();
        jMenuBar8 = new javax.swing.JMenuBar();
        jMenu19 = new javax.swing.JMenu();
        jMenu20 = new javax.swing.JMenu();
        jMenuBar9 = new javax.swing.JMenuBar();
        jMenu21 = new javax.swing.JMenu();
        jMenu22 = new javax.swing.JMenu();
        jMenuBar10 = new javax.swing.JMenuBar();
        jMenu23 = new javax.swing.JMenu();
        jMenu24 = new javax.swing.JMenu();
        jMenuBar11 = new javax.swing.JMenuBar();
        jMenu25 = new javax.swing.JMenu();
        jMenu26 = new javax.swing.JMenu();
        jMenuBar12 = new javax.swing.JMenuBar();
        jMenu27 = new javax.swing.JMenu();
        jMenu28 = new javax.swing.JMenu();
        jMenuBar13 = new javax.swing.JMenuBar();
        jMenu29 = new javax.swing.JMenu();
        jMenu30 = new javax.swing.JMenu();
        jMenuBar14 = new javax.swing.JMenuBar();
        jMenu31 = new javax.swing.JMenu();
        jMenu32 = new javax.swing.JMenu();
        jMenuBar15 = new javax.swing.JMenuBar();
        jMenu33 = new javax.swing.JMenu();
        jMenu34 = new javax.swing.JMenu();
        jMenuBar16 = new javax.swing.JMenuBar();
        jMenu35 = new javax.swing.JMenu();
        jMenu36 = new javax.swing.JMenu();
        jMenuBar17 = new javax.swing.JMenuBar();
        jMenu37 = new javax.swing.JMenu();
        jMenu38 = new javax.swing.JMenu();
        jMenuBar18 = new javax.swing.JMenuBar();
        jMenu39 = new javax.swing.JMenu();
        jMenu40 = new javax.swing.JMenu();
        jMenuBar19 = new javax.swing.JMenuBar();
        jMenu41 = new javax.swing.JMenu();
        jMenu42 = new javax.swing.JMenu();
        jMenuBar20 = new javax.swing.JMenuBar();
        jMenu43 = new javax.swing.JMenu();
        jMenu44 = new javax.swing.JMenu();
        jMenuBar21 = new javax.swing.JMenuBar();
        jMenu45 = new javax.swing.JMenu();
        jMenu46 = new javax.swing.JMenu();
        jMenuBar22 = new javax.swing.JMenuBar();
        jMenu47 = new javax.swing.JMenu();
        jMenu48 = new javax.swing.JMenu();
        jMenuBar23 = new javax.swing.JMenuBar();
        jMenu49 = new javax.swing.JMenu();
        jMenu50 = new javax.swing.JMenu();
        jMenuBar24 = new javax.swing.JMenuBar();
        jMenu51 = new javax.swing.JMenu();
        jMenu52 = new javax.swing.JMenu();
        jMenuBar25 = new javax.swing.JMenuBar();
        jMenu53 = new javax.swing.JMenu();
        jMenu54 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuBar26 = new javax.swing.JMenuBar();
        jMenu55 = new javax.swing.JMenu();
        jMenu56 = new javax.swing.JMenu();
        jMenuBar27 = new javax.swing.JMenuBar();
        jMenu57 = new javax.swing.JMenu();
        jMenu58 = new javax.swing.JMenu();
        jPanel2 = new javax.swing.JPanel();
        jMenuBar28 = new javax.swing.JMenuBar();
        jMenu59 = new javax.swing.JMenu();
        jMenu60 = new javax.swing.JMenu();
        jMenuBar29 = new javax.swing.JMenuBar();
        jMenu61 = new javax.swing.JMenu();
        jMenu62 = new javax.swing.JMenu();
        jMenuBar30 = new javax.swing.JMenuBar();
        jMenu63 = new javax.swing.JMenu();
        jMenu64 = new javax.swing.JMenu();
        jMenuBar31 = new javax.swing.JMenuBar();
        jMenu65 = new javax.swing.JMenu();
        jMenu66 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu67 = new javax.swing.JMenu();
        jMenu68 = new javax.swing.JMenu();
        jMenu69 = new javax.swing.JMenu();
        jMenu70 = new javax.swing.JMenu();
        jMenu71 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel_username = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Coursecount = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        studentcount = new javax.swing.JLabel();
        home = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu72 = new javax.swing.JMenu();
        jMenuItemAddCourse = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu73 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jMenu5.setText("jMenu5");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu7.setText("File");
        jMenuBar2.add(jMenu7);

        jMenu8.setText("Edit");
        jMenuBar2.add(jMenu8);

        jMenu9.setText("File");
        jMenuBar3.add(jMenu9);

        jMenu10.setText("Edit");
        jMenuBar3.add(jMenu10);

        jMenu11.setText("File");
        jMenuBar4.add(jMenu11);

        jMenu12.setText("Edit");
        jMenuBar4.add(jMenu12);

        jMenu13.setText("File");
        jMenuBar5.add(jMenu13);

        jMenu14.setText("Edit");
        jMenuBar5.add(jMenu14);

        jMenu15.setText("File");
        jMenuBar6.add(jMenu15);

        jMenu16.setText("Edit");
        jMenuBar6.add(jMenu16);

        jMenu17.setText("File");
        jMenuBar7.add(jMenu17);

        jMenu18.setText("Edit");
        jMenuBar7.add(jMenu18);

        jMenu19.setText("File");
        jMenuBar8.add(jMenu19);

        jMenu20.setText("Edit");
        jMenuBar8.add(jMenu20);

        jMenu21.setText("File");
        jMenuBar9.add(jMenu21);

        jMenu22.setText("Edit");
        jMenuBar9.add(jMenu22);

        jMenu23.setText("File");
        jMenuBar10.add(jMenu23);

        jMenu24.setText("Edit");
        jMenuBar10.add(jMenu24);

        jMenu25.setText("File");
        jMenuBar11.add(jMenu25);

        jMenu26.setText("Edit");
        jMenuBar11.add(jMenu26);

        jMenu27.setText("File");
        jMenuBar12.add(jMenu27);

        jMenu28.setText("Edit");
        jMenuBar12.add(jMenu28);

        jMenu29.setText("File");
        jMenuBar13.add(jMenu29);

        jMenu30.setText("Edit");
        jMenuBar13.add(jMenu30);

        jMenu31.setText("File");
        jMenuBar14.add(jMenu31);

        jMenu32.setText("Edit");
        jMenuBar14.add(jMenu32);

        jMenu33.setText("File");
        jMenuBar15.add(jMenu33);

        jMenu34.setText("Edit");
        jMenuBar15.add(jMenu34);

        jMenu35.setText("File");
        jMenuBar16.add(jMenu35);

        jMenu36.setText("Edit");
        jMenuBar16.add(jMenu36);

        jMenu37.setText("File");
        jMenuBar17.add(jMenu37);

        jMenu38.setText("Edit");
        jMenuBar17.add(jMenu38);

        jMenu39.setText("File");
        jMenuBar18.add(jMenu39);

        jMenu40.setText("Edit");
        jMenuBar18.add(jMenu40);

        jMenu41.setText("File");
        jMenuBar19.add(jMenu41);

        jMenu42.setText("Edit");
        jMenuBar19.add(jMenu42);

        jMenu43.setText("File");
        jMenuBar20.add(jMenu43);

        jMenu44.setText("Edit");
        jMenuBar20.add(jMenu44);

        jMenu45.setText("File");
        jMenuBar21.add(jMenu45);

        jMenu46.setText("Edit");
        jMenuBar21.add(jMenu46);

        jMenu47.setText("File");
        jMenuBar22.add(jMenu47);

        jMenu48.setText("Edit");
        jMenuBar22.add(jMenu48);

        jMenu49.setText("File");
        jMenuBar23.add(jMenu49);

        jMenu50.setText("Edit");
        jMenuBar23.add(jMenu50);

        jMenu51.setText("File");
        jMenuBar24.add(jMenu51);

        jMenu52.setText("Edit");
        jMenuBar24.add(jMenu52);

        jMenu53.setText("File");
        jMenuBar25.add(jMenu53);

        jMenu54.setText("Edit");
        jMenuBar25.add(jMenu54);

        jMenuItem3.setText("jMenuItem3");

        jMenu55.setText("File");
        jMenuBar26.add(jMenu55);

        jMenu56.setText("Edit");
        jMenuBar26.add(jMenu56);

        jMenu57.setText("File");
        jMenuBar27.add(jMenu57);

        jMenu58.setText("Edit");
        jMenuBar27.add(jMenu58);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 257, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 158, Short.MAX_VALUE)
        );

        jMenu59.setText("File");
        jMenuBar28.add(jMenu59);

        jMenu60.setText("Edit");
        jMenuBar28.add(jMenu60);

        jMenu61.setText("File");
        jMenuBar29.add(jMenu61);

        jMenu62.setText("Edit");
        jMenuBar29.add(jMenu62);

        jMenu63.setText("File");
        jMenuBar30.add(jMenu63);

        jMenu64.setText("Edit");
        jMenuBar30.add(jMenu64);

        jMenu65.setText("File");
        jMenuBar31.add(jMenu65);

        jMenu66.setText("Edit");
        jMenuBar31.add(jMenu66);

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu67.setText("jMenu67");

        jMenu68.setText("jMenu68");

        jMenu69.setText("jMenu69");

        jMenu70.setText("jMenu70");

        jMenu71.setText("jMenu71");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_username.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel_username.setText("Welcome <#####>");

        jPanel3.setBackground(new java.awt.Color(255, 102, 102));

        Coursecount.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        Coursecount.setForeground(new java.awt.Color(255, 255, 255));
        Coursecount.setText("Course Count =");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Coursecount, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(Coursecount, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        jPanel4.setBackground(new java.awt.Color(51, 153, 255));

        studentcount.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        studentcount.setForeground(new java.awt.Color(255, 255, 255));
        studentcount.setText("Students Count =");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(studentcount, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(studentcount, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        home.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        home.setText("HOME");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addComponent(jLabel_username)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_username, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(158, 158, 158))
        );

        jMenu6.setText("student");

        jMenuItem4.setText("Add");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem4);

        jMenuItem5.setText("Manage");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem5);

        jMenuBar1.add(jMenu6);

        jMenu72.setText("Course");

        jMenuItemAddCourse.setText("Add");
        jMenuItemAddCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAddCourseActionPerformed(evt);
            }
        });
        jMenu72.add(jMenuItemAddCourse);

        jMenuItem6.setText("Manage");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu72.add(jMenuItem6);

        jMenuBar1.add(jMenu72);

        jMenu73.setText("Score");

        jMenuItem7.setText("Add");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu73.add(jMenuItem7);

        jMenuItem8.setText("Edit / Delete");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu73.add(jMenuItem8);

        jMenuItem9.setText("Show Scores");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu73.add(jMenuItem9);

        jMenuBar1.add(jMenu73);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
  
  AddStudentForm Addsf = new AddStudentForm();
              Addsf.setVisible(true);
              Addsf.pack();
              Addsf.setLocationRelativeTo(null);
              Addsf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed

  manageStudentsForm mngsf = new manageStudentsForm();
              mngsf.setVisible(true);
              mngsf.pack();
              mngsf.setLocationRelativeTo(null);
              mngsf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItemAddCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAddCourseActionPerformed

  addCourseForm Addcf = new addCourseForm();
              Addcf.setVisible(true);
              Addcf.pack();
              Addcf.setLocationRelativeTo(null);
              Addcf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItemAddCourseActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed

  manageCourseForm mngcf = new manageCourseForm();
              mngcf.setVisible(true);
              mngcf.pack();
              mngcf.setLocationRelativeTo(null);
              mngcf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed

  addScoreForm AddSF = new addScoreForm();
              AddSF.setVisible(true);
              AddSF.pack();
              AddSF.setLocationRelativeTo(null);
              AddSF.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed

  editDeleteScore eddSF = new editDeleteScore();
              eddSF.setVisible(true);
              eddSF.pack();
              eddSF.setLocationRelativeTo(null);
              eddSF.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed

ShowScoresForm shsF = new ShowScoresForm();
              shsF.setVisible(true);
              shsF.pack();
              shsF.setLocationRelativeTo(null);
              shsF.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_jMenuItem9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel Coursecount;
    private javax.swing.JLabel home;
    public static javax.swing.JLabel jLabel_username;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu19;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu20;
    private javax.swing.JMenu jMenu21;
    private javax.swing.JMenu jMenu22;
    private javax.swing.JMenu jMenu23;
    private javax.swing.JMenu jMenu24;
    private javax.swing.JMenu jMenu25;
    private javax.swing.JMenu jMenu26;
    private javax.swing.JMenu jMenu27;
    private javax.swing.JMenu jMenu28;
    private javax.swing.JMenu jMenu29;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu30;
    private javax.swing.JMenu jMenu31;
    private javax.swing.JMenu jMenu32;
    private javax.swing.JMenu jMenu33;
    private javax.swing.JMenu jMenu34;
    private javax.swing.JMenu jMenu35;
    private javax.swing.JMenu jMenu36;
    private javax.swing.JMenu jMenu37;
    private javax.swing.JMenu jMenu38;
    private javax.swing.JMenu jMenu39;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu40;
    private javax.swing.JMenu jMenu41;
    private javax.swing.JMenu jMenu42;
    private javax.swing.JMenu jMenu43;
    private javax.swing.JMenu jMenu44;
    private javax.swing.JMenu jMenu45;
    private javax.swing.JMenu jMenu46;
    private javax.swing.JMenu jMenu47;
    private javax.swing.JMenu jMenu48;
    private javax.swing.JMenu jMenu49;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu50;
    private javax.swing.JMenu jMenu51;
    private javax.swing.JMenu jMenu52;
    private javax.swing.JMenu jMenu53;
    private javax.swing.JMenu jMenu54;
    private javax.swing.JMenu jMenu55;
    private javax.swing.JMenu jMenu56;
    private javax.swing.JMenu jMenu57;
    private javax.swing.JMenu jMenu58;
    private javax.swing.JMenu jMenu59;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu60;
    private javax.swing.JMenu jMenu61;
    private javax.swing.JMenu jMenu62;
    private javax.swing.JMenu jMenu63;
    private javax.swing.JMenu jMenu64;
    private javax.swing.JMenu jMenu65;
    private javax.swing.JMenu jMenu66;
    private javax.swing.JMenu jMenu67;
    private javax.swing.JMenu jMenu68;
    private javax.swing.JMenu jMenu69;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu70;
    private javax.swing.JMenu jMenu71;
    private javax.swing.JMenu jMenu72;
    private javax.swing.JMenu jMenu73;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar10;
    private javax.swing.JMenuBar jMenuBar11;
    private javax.swing.JMenuBar jMenuBar12;
    private javax.swing.JMenuBar jMenuBar13;
    private javax.swing.JMenuBar jMenuBar14;
    private javax.swing.JMenuBar jMenuBar15;
    private javax.swing.JMenuBar jMenuBar16;
    private javax.swing.JMenuBar jMenuBar17;
    private javax.swing.JMenuBar jMenuBar18;
    private javax.swing.JMenuBar jMenuBar19;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar20;
    private javax.swing.JMenuBar jMenuBar21;
    private javax.swing.JMenuBar jMenuBar22;
    private javax.swing.JMenuBar jMenuBar23;
    private javax.swing.JMenuBar jMenuBar24;
    private javax.swing.JMenuBar jMenuBar25;
    private javax.swing.JMenuBar jMenuBar26;
    private javax.swing.JMenuBar jMenuBar27;
    private javax.swing.JMenuBar jMenuBar28;
    private javax.swing.JMenuBar jMenuBar29;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar30;
    private javax.swing.JMenuBar jMenuBar31;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenuBar jMenuBar6;
    private javax.swing.JMenuBar jMenuBar7;
    private javax.swing.JMenuBar jMenuBar8;
    private javax.swing.JMenuBar jMenuBar9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuItemAddCourse;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public static javax.swing.JLabel studentcount;
    // End of variables declaration//GEN-END:variables
}
